name: test-snapd-debug-tools
summary: snapd and Ubuntu Core debug tools
description: |
  Collection of tools for debugging snapd and Ubuntu Core
version: 1.0.0
base: core24
confinement: strict

apps:
  tool:
    command: bin/cmd

parts:
  efitools:
    plugin: nil
    stage-packages:
      - efitools
    prime:
      - -usr/share/man

  keyctl:
    plugin: nil
    stage-packages:
      - keyutils
    prime:
      - -usr/share/man

  seccomp:
    plugin: nil
    stage-packages:
      # for scmp_sys_resolver
      - seccomp

  snapd:
    plugin: nil
    stage-packages:
      - snapd
    stage:
      # stage the snap binary for access to `snap debug api` command
      - usr/bin/snap

  snap-files:
    plugin: dump
    source: .
